### ISSUE TITLE
All data is there but the folders are empty

### ISSUE THREAD

**Issue by ChiRoXP** [jekil/awesome-hacking#17]
Same as issue #8. Possibly same causes. Any way to fix this?

**Comment by Sqwd** [comment]
Having the same issue. Tried to re-clone the list again today but folders still remain empty

**Comment by Sqwd** [comment]
Can anyone assist with this or have all the Dev's left?

**Comment by Sqwd** [comment]
Support Is dead use another bunch of tools

**Comment by jekil** [comment]
Are you using the command:

`git clone --recursive https://github.com/jekil/awesome-hacking.git`

to clone? (as in the documentation)

**Comment by mikiyasAyalew** [comment]
Tried to re-clone the list again  but folders still empty

**Comment by pedrobart** [comment]
> Are you using the command:
> 
> `git clone --recursive https://github.com/jekil/awesome-hacking.git`
> 
> to clone? (as in the documentation)

it work for me. 
thank you!

**Comment by Python9874** [comment]
same problem as me

**Comment by jekil** [comment]
Are you using the --recursive option?

As in

` git clone --recursive https://github.com/jekil/awesome-hacking.git`

**Comment by Python9874** [comment]
yes

**Comment by Python9874** [comment]
Let me say the error once it is done again

**Comment by Python9874** [comment]
Cloning into 'C:/Users/natha/awesome-hacking/Malware/Honeypot/cowrie'...
bash: line 1: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or directory
fatal: clone of 'https://github.com/micheloosterhof/cowrie.git' into submodule path 'C:/Users/natha/awesome-hacking/Malware/Honeypot/cowrie' failed
Failed to clone 'Malware/Honeypot/cowrie' a second time, aborting

C:\Users\natha>jjjjjjjjjjjjjjkmkmmkkmmkmkmkmkmkmkmmkkmkmmkkmkmkmmkmkmkmkmkm m m  m m   mnkjn n      n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
'jjjjjjjjjjjjjjkmkmmkkmmkmkmkmkmkmkmmkkmkmmkkmkmkmmkmkmkmkmkm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Python9874** [comment]
thats my error

**Comment by Python9874** [comment]
@jekil

**Comment by jekil** [comment]
There was an error related to some tools that changed their URLs. 
The git log was showing them. 
Next time please attach soon the log so the fix will be fast.

Tested and checked out now and it works. Thanks for reporting it.
