### ISSUE TITLE
Folder shows 14gb but folders inside empty

### ISSUE THREAD

**Issue by evil-pyth0n** [jekil/awesome-hacking#8]
It seems all the data is there but not shown. Maybe because of incomplete installation my all folders inside awesome-hacking.git showing empty. During installation some repos asked me for my github username & password and when i checked that github repositories they were not found (404 Not Found Error). So please how can i save my 14Gigs of downloaded data

**Comment by TheoWizman** [comment]
Did you use 'git clone --recursive' or the regular 'git clone' command ?

**Comment by jekil** [comment]
I can confirm this is an issue. Tools changes, and also their repository, during time issue like this can happen. I will fix it this weekend and keep you updated.
Thank you very much for reporting it!

**Comment by jekil** [comment]
It is now fixed. Thanks very much for reporting.
